### ISSUE TITLE
Can't install on  craftcms/cms 3.0.1

### ISSUE THREAD

**Issue by sergeifilippov** [putyourlightson/craft-amazon-ses#1]
Hi,

Trying to install using ` composer require putyourlightson/craft-amazon-ses` but every time I get the stability mismatch error.

```
[InvalidArgumentException]
Could not find a matching version of package putyourlightson/craft-amazon-ses.
Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).
```
- Craf: Pro **3.0.1**
- PHP 7.1.16

What other info do you need?

**Comment by putyourlightson** [comment]
Ah yes, I hadn't added the latest stable version to packagist. It should work for you now.

**Comment by sergeifilippov** [comment]
Yep worked. 👍🏻Cheers.
