### ISSUE TITLE
Unable to use environment variables in configurationSet

### ISSUE THREAD

**Issue by sebschaefer** [putyourlightson/craft-amazon-ses#12]
### Describe the bug
It's not possible to use env var in setting "configurationSet" (though it has suggestEnvVars:true). 
Variable will be send unparsed to SES which results in an error.

### To reproduce
Steps to reproduce the behaviour:
1. Go to "Settings -> Email", Choose Amazon SES as Transport Type
2. Use an .env variable in setting "Configuration Set"
2. Click on "Test"
3. See error message "There was an error testing your email settings." 
    (Captured AwsException: ``` InvalidParameterValue (client): Invalid configuration set name <$...```)

### Versions
- Plugin version: 1.3.2
- Craft version: 3.5.17.1

**Comment by bencroker** [comment]
Thanks, fixed in https://github.com/putyourlightson/craft-amazon-ses/commit/a4f1de46610d2921196bfb35ba53669daf62329e and released in 1.3.3.
