### ISSUE TITLE
Test emails fail after upgrading to Craft 4

### ISSUE THREAD

**Issue by daveyjones** [putyourlightson/craft-amazon-ses#14]
### Describe the bug
After upgrading to Craft 4, any attempt to send a test email from the plugin settings page results in the following error:

> Invalid option(s) "version", "credentials" passed to "AsyncAws\Core\Configuration::AsyncAws\Core\Configuration::create".

### To reproduce
Steps to reproduce the behaviour:
1. Upgrade to Craft 4
2. Navigate to Settings > Email
3. Press the "Test" button
4. See the error

### Expected behaviour
No error and test email sent.

### Screenshots

<img width="1391" alt="Screen Shot 2022-05-17 at 9 47 18 AM" src="https://user-images.githubusercontent.com/2852617/168867337-0c4614b4-43f8-401a-a615-c130d0fa306d.png">

### Versions
- Plugin version: 2.0.0
- Craft version: 4.0.2

**Comment by bencroker** [comment]
Thanks for reporting this! Fixed in https://github.com/putyourlightson/craft-amazon-ses/commit/1ad2da44656cb025e47b34bc3da38599a85beb1b and released in version 2.0.1. Can you please that this the plugin is now sending test emails?

**Comment by daveyjones** [comment]
Just tested and it works great. Thanks!
