### ISSUE TITLE
 Unable to send an email: Missing Authentication Token

### ISSUE THREAD

**Issue by arifje** [putyourlightson/craft-amazon-ses#15]
Did a basic installation like the example, added the region, sent a test email, got this error in the CP:

There was an error testing your email settings.

Logs:

2024-04-01 19:08:58 [web.ERROR] [yii\symfonymailer\Mailer::sendMessage] Unable to send an email: Missing Authentication Token (code MissingAuthenticationTokenException). {"memory":21149432} 

Account at SES is activated, running in production, no limits.

<img width="1321" alt="Screenshot 2024-04-01 at 19 11 30" src="https://github.com/putyourlightson/craft-amazon-ses/assets/1286410/1d186868-7743-4505-b46b-168d62b5744d">

What am I missing?

**Comment by bencroker** [comment]
Have you provided an API key and secret in the mailer transport settings (or is a valid credential provider chain present)?

**Comment by arifje** [comment]
Just did, then it works! 

But I got confused by the example/docs which says API keys are not required, but apparently they are :-)

**Comment by bencroker** [comment]
They are not required, provided a credential provider chain is present.

![screenshot-rS3hvDk2@2x](https://github.com/putyourlightson/craft-amazon-ses/assets/57572400/706fe6d9-c530-433c-9f4e-f6e5dd90c09c)
