### ISSUE TITLE
Error testing email settings

### ISSUE THREAD

**Issue by Emkaytoo** [putyourlightson/craft-amazon-ses#2]
I've recently installed the SES plugin on **Craft 3.0.10.3**, and I'm unable to send test emails. I get the error `There was an error testing your email settings`. I have tried with two sets of credentials on two accounts.

I'm not sure where to go from here. I was able to authenticate a non-Amazon-SES email platform through SMTP, but my client wants to use SES.

**Comment by putyourlightson** [comment]
Can you check what the exact error message is in the Craft debugger?

![screen shot 2018-06-12 at 22 42 42](https://user-images.githubusercontent.com/2318222/41316199-058c6c4e-6e92-11e8-8692-7917c3bd882b.png)

**Comment by putyourlightson** [comment]
Any update on this?

**Comment by michaelroper** [comment]
@Emkaytoo, just in case you had the same problem as me - my Craft 2 site was sending using AWS SES, but in that instance it was using SMTP user creds that I'd created in SES. When I tried to use those same creds with this plugin, it errored on testing. Instead, it was needing my IAM user creds - when i put them in, it worked!

**Comment by putyourlightson** [comment]
Yeah SES credentials can be tricky. Try it with IAM and AmazonSESFullAccess policy in place.

**Comment by Emkaytoo** [comment]
Sorry to ghost, but we figured out what was happening. This may be an issue with the plugin or could be Craft or Amazon SES config... I'm not sure.

What had happened was:
1. Create user `admin` and email `admin@agency.com`
1. Create SES user `info@client.com`
1. Install plugin and add credentials, test, and fail.
1. Test many, many times, all failure.
1. Create user `clientAdmin` using `info@client.com` and test, and succeed.

I think when sending the test email, the plugin/CMS was using the credentials for our agency admin account (as it was the active user) instead of the settings in the plugin/SMTP settings. Once we created a Craft account with the same email as the SES user, _and then tested from that account_, it was able to authenticate and send the test email.

This happened on both vanilla SMTP settings as well as using your plugin, so I suspect this is an issue with Craft (or maybe that's just how it's supposed to work). But given that I could authenticate a Mandrill account but not SES from the vanilla SMTP settings, I'm guessing it's how the system and SES are communicating. 

It doesn't make sense that an admin-level user would be barred from testing email settings because they don't have the same login as the email sending platform, despite the proper settings in place.

**Comment by putyourlightson** [comment]
Thanks for the detailed response. I'm not sure that that really was the issue though, as the _System Email Address_ definitely is used as the from email address (and not the user's email). What might be happening though is that the _recipient email address_, which is the user's email address, is being rejected.

From the [docs](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/ses-errors.html):

> If your account is still in the Amazon SES sandbox, you also must verify every recipient email address except for the recipients provided by the Amazon SES mailbox simulator.
