### ISSUE TITLE
Not require API Key/Secret

### ISSUE THREAD

**Issue by nateiler** [putyourlightson/craft-amazon-ses#3]
Technically, an API Key/Secret is not required if you configure AWS Groups/Roles/Permissions to allow your AWS app instance(s) to communicate with SES.

This is also the case with many AWS services (such as S3, etc).

Thoughts on removing these fields as required?  Happy to do a pull request as well (as long as you'll entertain accepting it).

**Comment by putyourlightson** [comment]
Thanks Nate, changed in https://github.com/putyourlightson/craft-amazon-ses/commit/ec73175a3803c2f69878ab420e9bf97992b4230e

**Comment by nateiler** [comment]
Awesome Ben!  Thanks!
