### ISSUE TITLE
[FR] Add ConfigurationSetName option

### ISSUE THREAD

**Issue by timkelty** [putyourlightson/craft-amazon-ses#5]
To hook into SES event, you need to create an "SES Configuration Set" and then pass that when sending an email (eg if you want to get a notification when an email is bounced): https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-configuration-sets-in-email.html

Would be great if there were a `ConfigurationSetName` setting that would add that header to sent mail.

**Comment by putyourlightson** [comment]
Thanks, I'll look into adding this as a config setting.

**Comment by putyourlightson** [comment]
Added in 1.2.0 https://github.com/putyourlightson/craft-amazon-ses/commit/5c6c87be217f3a07fbf64a54342c3f39efc89687
