### ISSUE TITLE
Additional Regions

### ISSUE THREAD

**Issue by phpsa** [putyourlightson/craft-amazon-ses#7]
Could the plugin please be updated to include the new regions availalble speciically ap-southeast-1 / 2

**Comment by bencroker** [comment]
Just released [1.3.0](https://github.com/putyourlightson/craft-amazon-ses/blob/v1/CHANGELOG.md#130---2020-01-28) with some new regions, including `ap-southeast-2`. 

For reference, the currently supported regions are listed here:
https://docs.aws.amazon.com/general/latest/gr/ses.html
